# Generated by Django 5.2.6 on 2025-10-08 11:29

import backoffice.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=150)),
                ('image', models.ImageField(upload_to=backoffice.models.portfolio_image_upload_to)),
                ('tags', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'image_asset',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'portfolio',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.imageasset')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.portfolio')),
            ],
            options={
                'db_table': 'portfolio_image_link',
                'ordering': ['portfolio__order', 'order', 'id'],
                'unique_together': {('portfolio', 'image')},
            },
        ),
        migrations.AddField(
            model_name='imageasset',
            name='portfolios',
            field=models.ManyToManyField(blank=True, related_name='images', through='backoffice.PortfolioImage', to='backoffice.portfolio'),
        ),
    ]
