# Generated by Django 5.2.6 on 2025-10-09 12:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'db_table': 'service_showcase',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ShowcaseItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('limit', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.portfolio')),
                ('showcase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='backoffice.showcase')),
            ],
            options={
                'db_table': 'service_showcase_item',
                'ordering': ['showcase__order', 'order', 'id'],
                'unique_together': {('showcase', 'portfolio')},
            },
        ),
    ]
