"""
Django settings for drnahsap project.

Generated by 'django-admin startproject' using Django 5.2.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-$0%r6ibw4)a@c5tk)p$ai20z3t!p0mm^ab6w!_^cz7zx09!q^u'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'main',
    'backoffice',

]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',  # 👈 EKLE
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'drnahsap.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates']
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'drnahsap.wsgi.application'

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

# settings.py
LANGUAGE_CODE = 'tr'  # 'tr-tr' da olur ama kısası yaygın
TIME_ZONE = 'Europe/Istanbul'  # UTC yerine yerel saat dilimi
USE_I18N = True
USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/


STATIC_URL = '/static/'

# Proje geliştirme sırasında (development)
STATICFILES_DIRS = [
    BASE_DIR / "static",  # uygulama dışındaki ortak static dosyaların yolu
]

# collectstatic ile toplanacak klasör (production için zorunlu)
STATIC_ROOT = BASE_DIR / "staticfiles"

# Kullanıcı tarafından yüklenen medya dosyaları (opsiyonel ama tavsiye edilir)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Oturum tarayıcı kapanınca sonlansın
SESSION_EXPIRE_AT_BROWSER_CLOSE = True

LOGIN_URL = "/yonetici/"
LOGIN_REDIRECT_URL = "/yonetici/panel/"

# Toplam POST gövdesi limiti
# Geliştirmede sınırsız yapmak için None verebilirsin:
DATA_UPLOAD_MAX_MEMORY_SIZE = None  # veya 2 * 1024 * 1024 * 1024  (2GB)

# Tek dosyanın RAM'de tutulma eşiği (üstünü disk temp'e yazar)
FILE_UPLOAD_MAX_MEMORY_SIZE = 50 * 1024 * 1024  # 50 MB (foto için güvenli)

# Çok alanlı formlar için sınır
DATA_UPLOAD_MAX_NUMBER_FIELDS = 50000

# Geçici upload klasörü (diskte bol alan olan bir yer seç)
FILE_UPLOAD_TEMP_DIR = BASE_DIR / "tmp_uploads"
