# Generated by Django 5.2.6 on 2025-09-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_class', models.CharField(blank=True, max_length=64)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='main.projectcategory')),
            ],
        ),
    ]
