# Generated by Django 5.2.6 on 2025-10-08 10:06

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProjectCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('slug', models.SlugField(unique=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('icon_class', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'verbose_name': 'Proje Kategorisi',
                'verbose_name_plural': 'Proje Kategorileri',
                'db_table': 'project_categories',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('short_description', models.CharField(blank=True, max_length=200)),
                ('cover', models.ImageField(blank=True, null=True, upload_to='projects/covers/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='projects', to='main.projectcategory')),
            ],
            options={
                'verbose_name': 'Proje',
                'verbose_name_plural': 'Projeler',
                'db_table': 'projects',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.project_gallery_upload_to)),
                ('kind', models.CharField(choices=[('before', 'Öncesi'), ('after', 'Sonrası'), ('during', 'Uygulama'), ('final', 'Final'), ('render', 'Render'), ('other', 'Diğer')], default='other', max_length=10)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pair_key', models.CharField(blank=True, help_text="Aynı anahtardaki BEFORE & AFTER görselleri slider'da eşleşir (örn: 'mutfak-1').", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project')),
            ],
            options={
                'verbose_name': 'Proje Görseli',
                'verbose_name_plural': 'Proje Görselleri',
                'db_table': 'project_images',
                'ordering': ('order', 'id'),
            },
        ),
    ]
