# Generated by Django 5.2.6 on 2025-09-23 13:41

import django.db.models.deletion
import main.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcategory',
            options={},
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='icon_class',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='slug',
            field=models.SlugField(unique=True),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=main.models.project_gallery_upload_to)),
                ('kind', models.CharField(choices=[('before', 'Öncesi'), ('after', 'Sonrası'), ('during', 'Uygulama'), ('final', 'Final'), ('render', 'Render'), ('other', 'Diğer')], default='other', max_length=10)),
                ('title', models.CharField(blank=True, max_length=150)),
                ('alt_text', models.CharField(blank=True, max_length=150)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('pair_key', models.CharField(blank=True, help_text="Aynı anahtardaki BEFORE & AFTER görselleri slider'da eşleşir (örn: 'mutfak-1').", max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='main.project')),
            ],
            options={
                'ordering': ('order', 'id'),
            },
        ),
    ]
