# Generated by Django 5.2.6 on 2025-09-29 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_projectcategory_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=30, null=True)),
                ('subject', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'İletişim Mesajı',
                'verbose_name_plural': 'İletişim Mesajları',
                'db_table': 'contact_messages',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['id'], 'verbose_name': 'Proje', 'verbose_name_plural': 'Projeler'},
        ),
        migrations.AlterModelOptions(
            name='projectcategory',
            options={'ordering': ['order', 'id'], 'verbose_name': 'Proje Kategorisi', 'verbose_name_plural': 'Proje Kategorileri'},
        ),
        migrations.AlterModelOptions(
            name='projectimage',
            options={'ordering': ('order', 'id'), 'verbose_name': 'Proje Görseli', 'verbose_name_plural': 'Proje Görselleri'},
        ),
        migrations.AlterModelTable(
            name='project',
            table='projects',
        ),
        migrations.AlterModelTable(
            name='projectcategory',
            table='project_categories',
        ),
        migrations.AlterModelTable(
            name='projectimage',
            table='project_images',
        ),
    ]
